config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "projects#index"
  resources "users", only: ["show", "index"]
  resources "skills"
  resources "projects"
  resources "posts" do
    resources "comments", except: ["show", "index"]
  end
  resources "references"
end

app/models/comment.rb
class Comment < ActiveRecord::Base
belongs_to :user
belongs_to :post

validates :description, presence: true
validates :description, uniqueness: true
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  before_action :authenticate_user!

  def new
    @post = Post.find(params[:post_id])
    @comment = @post.comments.new
    respond_to do |format|
      format.html { redirect_to post_path(@post)}
      format.js
    end

  end

  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.new(comment_params)
    if @comment.save
      @comments = @post.comments.all
      respond_to do |format|
        format.html { redirect_to post_path(@post) }
        format.js
      end
    else
      render :new
    end
  end

  def edit
    @post = Post.find(params[:post_id])
    @comment = Comment.find(params[:id])
  end

  def update
    @post = Post.find(params[:post_id])
    @comment = Comment.find(params[:id])
    if @comment.update(comment_params)
      flash[:notice] = "Comment Modified"
      redirect_to post_path(@post)
    else
      render :edit
    end
  end

  def destroy
    @post = Post.find(params[:post_id])
    @comment = Comment.find(params[:id])
    @comment.destroy
    redirect_to post_path(@post)
  end

  private
   def comment_params
    params.require(:comment).permit!
  end

end

app/views/comments/_form.html.erb
<%= render 'layouts/errors', object: @comment %>

<%= bootstrap_form_for [@post, @comment], remote: true do |f| %>
  <%= f.text_area :description %>
  <%= f.hidden_field :user_id, value: current_user.id %>
  <%= f.submit data: {disable_with: "Posting..." }, class: "btn btn-success btn-block" %>
<% end %>

app/views/comments/_list.html.erb
<% if @post.comments.any? %>
  <% @post.comments.each do |comment| %>
    <p><%= link_to comment.user.email, user_path(comment.user)  %> replies: <%= comment.description  %>
    <% if is_admin? || current_user == comment.user %>
      <%= link_to edit_post_comment_path(@post, comment) do %>
        <span class="glyphicon glyphicon-edit orange"></span>
      <% end %>
      <%= link_to post_comment_path(@post, comment), id: "delete_comment_#{comment.id}", data: {confirm: "Destroy Comment?", method: 'delete'} do %>
        <span class="glyphicon glyphicon-remove-sign red"></span>
      <% end %>
    <% end %>
    </p>
  <% end %>
<% end %>

app/views/comments/create.js.erb
$('#comment_form').hide();
$('#add_comment_button').show();
$('#comments_list').html("<%= j render('list') %>");

app/views/comments/edit.html.erb
<% content_for(:title, "Edit | PORTFOLIO")  %>
<h1>Edit <%= @comment.description %></h1>

<%= render 'form' %>

app/views/comments/new.html.erb
<%= content_for(:title, "New Post | PORTFOLIO") %>

<h1>Create New Comment</h1>

<%= render 'form' %>

app/views/comments/new.js.erb
$('#add_comment_button').hide();
$('#comment_form').show();
$('#comment_form').html("<%= j render('form') %>")