config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "projects#index"
  resources "users", only: ["show", "index"]
  resources "skills"
  resources "projects"
  resources "posts" do
    resources "comments", except: ["show", "index"]
  end
  resources "references"
end

app/models/project.rb
class Project < ActiveRecord::Base
  has_and_belongs_to_many :skills

  validates :name, presence: true
  validates :name, uniqueness: true
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

  before_action :authenticate_user!

  def index
    @projects = Project.all
  end

  def show
    @project = Project.find(params[:id])
  end

  def new
    if is_admin?
      @project = Project.new
    else
      flash[:alert] = "You must be an administrator to access these functions"
      redirect_to :back
    end
  end

  def create
    @project = Project.new(project_params)
    if @project.save
      flash[:noitce] = "Project Added"
      redirect_to project_path(@project)
    else
      render :new
    end
  end

  def edit
    if is_admin?
      @project = Project.find(params[:id])
      @skills = Skill.all
    else
      flash[:alert] = "You must be an administrator to access these functions"
      redirect_to :back
    end
  end

  def update
    @project = Project.find(params[:id])
    if @project.update(project_params)
      flash[:notice] = "Project Modified"
      redirect_to project_path(@project)
    else
      render :edit
    end
  end

  def destroy
    @project = Project.find(params[:id])
    @project.destroy
    redirect_to projects_path
  end

  private
   def project_params
    params.require(:project).permit!
    # Need to figure out how to accept :skill_ids as an array without global permit! hack
    # (:name, :github_link, :live_link, :skill_ids) --- not working, Error : skill_ids not permitted
  end

end

app/views/projects/_form.html.erb
<%= render 'layouts/errors', object: @project %>

<%= bootstrap_form_for(@project) do |f| %>
  <%= f.text_field :name %>
  <%= f.text_area :description %>
  <%= f.text_field :github_link %>
  <%= f.text_field :live_link %>
  <% if @project.id != nil %>
    <% if @skills.any? %>
      <%= f.collection_check_boxes(:skill_ids, @skills, :id, :name) %>
    <% end %>
  <% end %>
  <%= f.submit data: {disable_with: "Projectorizing..." }, class: "btn btn-success btn-block" %>
<% end %>

app/views/projects/edit.html.erb
<% content_for(:title, "Edit | PORTFOLIO")  %>
<h1>Edit <%= @project.name %></h1>

<%= render 'form' %>

app/views/projects/index.html.erb
<% content_for(:title, "Projects | PORTFOLIO")  %>

<h1>Projects</h1>

<ul>
  <% @projects.each do |project| %>
    <li>
      <%= link_to project.name, project_path(project) %>
      <% if is_admin? %>
        <%= link_to edit_project_path(project) do %>
          <span class="glyphicon glyphicon-edit orange"></span>
        <% end %>
        <%= link_to project_path(project), data: {confirm: "Destroy Project?", method: 'delete'} do %>
          <span class="glyphicon glyphicon-remove-sign red"></span>
        <% end %>
      <% end %>
    </li>
  <% end %>
</ul>

app/views/projects/new.html.erb
<%= content_for(:title, "New Project | PORTFOLIO") %>

<h1>Create New Project</h1>

<%= render 'form' %>

app/views/projects/show.html.erb
<%= content_for(:title, "#{@project.name} | PORTFOLIO") %>

<h1><%= @project.name %></h1>
<ul>
  <% if @project.github_link %>
    <li>Github: <%= @project.github_link %></li>
  <% end %>
  <% if @project.live_link %>
    <li>Live: <%= @project.live_link %></li>
  <% end %>
  <% if @project.skills.any? %>
    <li>Skills:</li>
      <ul>
        <% @project.skills.each do |skill| %>
        <li><%= link_to skill.name, skill_path(skill) %></li>
        <% end %>
      </ul>
  <% end %>
</ul>

<% if is_admin? %>
  <div class="btn-group btn-group-sm " role="group">
    <%= link_to "Edit", edit_project_path(@project), class: "btn btn-warning" %>
    <%= link_to "Delete", project_path(@project), class: "btn btn-danger",
                                          data: {confirm: "Destroy Project?",
                                                  method: 'delete'} %>
  </div>
<% end %>