config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "projects#index"
  resources "users", only: ["show", "index"]
  resources "skills"
  resources "projects"
  resources "posts" do
    resources "comments", except: ["show", "index"]
  end
  resources "references"
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
  has_many :comments

  validates :name, presence: true
  validates :name, uniqueness: true
  validates :description, presence: true
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  before_action :authenticate_user!

  def index
    @posts = Post.all
  end

  def show
    @post = Post.find(params[:id])
  end

  def new
    if is_admin?
      @post = Post.new
    else
      flash[:alert] = "You must be an administrator to access these functions"
      redirect_to root_path
    end
  end

  def create
    @post = Post.new(post_params)
    if @post.save
      flash[:notice] = "Post Added"
      redirect_to post_path(@post)
    else
      render :new
    end
  end

  def edit
    if is_admin?
      @post = Post.find(params[:id])
    else
      flash[:alert] = "You must be an administrator to access these functions"
      redirect_to root_path
    end
  end

  def update
    @post = Post.find(params[:id])
    if @post.update(post_params)
      flash[:notice] = "Post Modified"
      redirect_to post_path(@post)
    else
      render :edit
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to posts_path
  end

  private
   def post_params
    params.require(:post).permit!
  end

end

app/views/posts/_form.html.erb
<%= render 'layouts/errors', object: @post %>

<%= bootstrap_form_for(@post) do |f| %>
  <%= f.text_field :name %>
  <%= f.text_area :description %>
  <%= f.hidden_field :user_id, value: current_user.id %>
  <%= f.submit data: {disable_with: "Posting..." }, class: "btn btn-success btn-block" %>
<% end %>

app/views/posts/edit.html.erb
<% content_for(:title, "Edit | PORTFOLIO")  %>
<h1>Edit <%= @post.name %></h1>

<%= render 'form' %>

app/views/posts/index.html.erb
<% content_for(:title, "Posts | PORTFOLIO")  %>

<h1>Posts</h1>

<ul>
  <% @posts.each do |post| %>
    <li>
      <%= link_to post.name, post_path(post) %>
      <% if is_admin? || current_user == post.user %>
        <%= link_to edit_post_path(post) do %>
          <span class="glyphicon glyphicon-edit orange"></span>
        <% end %>
        <%= link_to post_path(post), data: {confirm: "Destroy Post?", method: 'delete'} do %>
          <span class="glyphicon glyphicon-remove-sign red"></span>
        <% end %>
      <% end %>
    </li>
  <% end %>
</ul>

app/views/posts/new.html.erb
<%= content_for(:title, "New Post | PORTFOLIO") %>

<h1>Create New Post</h1>

<%= render 'form' %>

app/views/posts/show.html.erb
<%= content_for(:title, "#{@post.name} | PORTFOLIO") %>

<h1><%= @post.name %></h1>
<p>
  Posted by: <%= link_to @post.user.email, user_path(@post.user) %>
</p>
<hr>
<p>
  <%= @post.description %>
</p>
<hr>

<div id="comments_list">
  <%= render 'comments/list' %>
</div>

<hr>

<%= link_to "Reply", new_post_comment_path(@post), remote: true, class: "btn btn-info", id: "add_comment_button"%>
<div id="comment_form">
</div>

<hr>

<% if is_admin? || current_user == @post.user %>
  <div class="btn-group btn-group-sm " role="group">
    <%= link_to "Edit", edit_post_path(@post), class: "btn btn-warning" %>
    <%= link_to "Delete", post_path(@post), class: "btn btn-danger",
                                          data: {confirm: "Destroy Post?",
                                                  method: 'delete'} %>
  </div>
<% end %>