config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "projects#index"
  resources "users", only: ["show", "index"]
  resources "skills"
  resources "projects"
  resources "posts" do
    resources "comments", except: ["show", "index"]
  end
  resources "references"
end

app/views/layouts/_errors.html.erb

<% if object.errors.any? %>
 <h3>You done messed up.</h3>
 <ul>
   <% object.errors.full_messages.each do |message| %>
   <li><%= message %></li>
   <% end %>
 </ul>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
<title><%= yield(:title) %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="container">
  <div class="text-center">

       <strong class="red"><%= flash[:alert] %></strong>
       <strong class="orange"><%= flash[:notice] %></strong>
   </div>
<%= yield %>
</div>



<!--  <nav class='navbar navbar-default' role='navigation' id="nav-footer">
      <ul class='nav navbar-nav'>
        <li><%= link_to "Skills", skills_path %></li>
        <li><%= link_to "New Skill", new_skill_path %></li>
        <li><%= link_to "Projects", projects_path %></li>
        <li><%= link_to "New Project", new_project_path %></li>
      </ul>
    </nav> -->



    <nav class="navbar navbar-default" role="navigation">
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
  </div>
    <a class="navbar-brand" href="/#">Home</a>
    <div class="navbar-collapse collapse">
      <% if user_signed_in? %>
        <ul class="nav navbar-nav navbar-left">
            <li><%= link_to "Skills", skills_path %></li>
            <li><%= link_to "New Skill", new_skill_path %></li>
            <li><%= link_to "Projects", projects_path %></li>
            <li><%= link_to "New Project", new_project_path %></li>
            <li><%= link_to "Posts", posts_path %></li>
            <li><%= link_to "New Post", new_post_path %></li>
            <li><%= link_to "References", references_path %><li>
        </ul>
      <% end %>
    <ul class="nav navbar-nav navbar-right">
      <% if user_signed_in? %>
        <li>Logged in as <strong><%= current_user.email %></strong></li>
        <li><%= link_to 'Edit profile', edit_user_registration_path %></li>
        <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
      <% else %>
        <li><%= link_to "Sign up", new_user_registration_path %></li>
        <li><%= link_to "Login", new_user_session_path %></li>
      <% end %>
    </ul>
  </div>
</nav>



</body>
</html>